---
language:
  - node_js

node_js:
  - "8"

env:
  - NODE_VERSION=8

before_install:
install:
  - yarn install

before_script:
script:
  - yarn ci

after_script:
notifications:
  email:
    on_success: never
    on_failure: always